name: Semgrep Scans with .NET lock files

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  restore:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'

      - name: Restore dependencies
        run: dotnet restore src/Web/Web.csproj -p:RestorePackagesWithLockFile=True # Specify the .csproj file

      - name: Upload Lock File    
        uses: actions/upload-artifact@v3
        with:
          name: lockfile
          path: 'src/Web/packages.lock.json' # Adjust path if necessary

  semgrep:
    needs: restore
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: lockfile 

      - name: Run Semgrep
        run: semgrep ci
